export const data = [
    { text: "I loved the way you explained that concept!", label: "positive" },
    { text: "Great job on the pacing of this video.", label: "positive" },
    { text: "Your tips were really helpful, thanks!", label: "positive" },
    { text: "I appreciate the time and effort you put into making this video.", label: "positive" },
    { text: "I learned so much from your video, thank you.", label: "positive" },
    { text: "Your advice was spot on, I'll be trying that out.", label: "positive" },
    { text: "I laughed out loud at your sense of humor.", label: "positive" },
    { text: "Your video inspired me to try something new.", label: "positive" },
    { text: "The visuals in your video were amazing.", label: "positive" },
    { text: "I can tell you put a lot of thought into this video.", label: "positive" },
    { text: "This video was just okay.", label: "neutral" },
    { text: "I didn't have a strong reaction to your video.", label: "neutral" },
    { text: "Your video was informative, but nothing special.", label: "neutral" },
    { text: "I didn't find your tips particularly helpful.", label: "neutral" },
    { text: "I can't say I loved or hated your video.", label: "neutral" },
    { text: "Your video was just average.", label: "neutral" },
    { text: "I have mixed feelings about your advice.", label: "neutral" },
    { text: "I didn't find your video particularly entertaining.", label: "neutral" },
    { text: "Your video was informative, but not memorable.", label: "neutral" },
    { text: "I don't have a strong opinion on your video.", label: "neutral" },
    { text: "I was really disappointed with your video.", label: "negative" },
    { text: "Your tips were not useful at all.", label: "negative" },
    { text: "Your video was a waste of time.", label: "negative" },
    { text: "I was let down by the quality of your video.", label: "negative" },
    { text: "Your video was poorly made.", label: "negative" },
    { text: "I didn't find your video to be helpful.", label: "negative" },
    { text: "Your video was not interesting.", label: "negative" },
    { text: "I was bored by your video.", label: "negative" },
    { text: "Your advice was misguided.", label: "negative" },
    { text: "Your video was not well-received.", label: "negative" },
    { text: "You did a fantastic job with this video!", label: "positive" },
    { text: "Your tips were exactly what I needed to hear.", label: "positive" },
    { text: "I loved your sense of humor in this video.", label: "positive" },
    { text: "Your video was a great source of inspiration.", label: "positive" },
    { text: "I learned so much from your tips.", label: "positive" },
    { text: "Your video was highly entertaining.", label: "positive" },
    { text: "I appreciated the time you took to make this video.", label: "positive" },
    { text: "Your video was a real eye-opener.", label: "positive" },
    { text: "I can tell you put a lot of heart into this video.", label: "positive" },
    { text: "I had no strong reaction to your video.", label: "neutral" },
    { text: "Your video was just average.", label: "neutral" },
    { text: "I didn't find your advice particularly useful.", label: "neutral" },
    { text: "I have mixed feelings about your video.", label: "neutral" },
    { text: "Your video was not particularly noteworthy.", label: "neutral" },
    { text: "I didn't find your video to be very interesting.", label: "neutral" },
    { text: "Your video was just okay.", label: "neutral" },
    { text: "I have no strong opinions on your advice.", label: "neutral" },
    { text: "Your video was not memorable.", label: "neutral" },
    { text: "The video is mediocre.", label: "neutral" },
    { text: "I didn't have a strong reaction to this video.", label: "neutral" },
    { text: "The video is just average.", label: "neutral" },
    { text: "This video didn't leave much of an impression on me.", label: "neutral" },
    { text: "I have no opinion on this video.", label: "neutral" },
    { text: "This video is nothing special.", label: "neutral" },
    { text: "The video is just okay.", label: "neutral" },
    { text: "This video is not particularly noteworthy.", label: "neutral" },
    { text: "I found the video to be just average.", label: "neutral" },
    { text: "I had no emotional response to this video.", label: "neutral" },
    { text: "The video was uninteresting.", label: "negative" },
    { text: "I was not impressed by this video.", label: "negative" },
    { text: "This video was boring.", label: "negative" },
    { text: "I found the video to be a waste of time.", label: "negative" },
    { text: "The video was not good.", label: "negative" },
    { text: "I did not enjoy this video.", label: "negative" },
    { text: "This video was disappointing.", label: "negative" },
    { text: "I was not entertained by this video.", label: "negative" },
    { text: "The video was not up to my expectations.", label: "negative" },
    { text: "I didn't like this video.", label: "negative" },
    { text: "This video was unsatisfactory.", label: "negative" },
    { text: "I found the video to be poorly made.", label: "negative" },
    { text: "The video was subpar.", label: "negative" },
    { text: "I was not a fan of this video.", label: "negative" },
    { text: "This video was underwhelming.", label: "negative" },
    { text: "I was not impressed with this video.", label: "negative" },
    { text: "The video was not well-made.", label: "negative" },
    { text: "I found the video to be lacking.", label: "negative" },
    { text: "This video was below average.", label: "negative" },
    { text: "I was not pleased with this video.", label: "negative" },
    { text: "The video was poorly executed.", label: "negative" },
    { text: "The video was just okay.", label: "neutral" },
    { text: "I had no strong opinion on this video.", label: "neutral" },
    { text: "This video was nothing exceptional.", label: "neutral" },
    { text: "I didn't have an emotional response to this video.", label: "neutral" },
    { text: "The video was just average.", label: "neutral" },
    { text: "This video didn't make much of an impression on me.", label: "neutral" },
    { text: "I found the video to be average.", label: "neutral" },
    { text: "The video was okay, but not great.", label: "neutral" },
    { text: "I have a neutral opinion on this video.", label: "neutral" },
    { text: "This video was neither good nor bad.", label: "neutral" },
    { text: "I didn't dislike the video, but I didn't love it either.", label: "neutral" },
    { text: "The video was okay, but forgettable.", label: "neutral" },
    { text: "I didn't have a strong reaction to this video.", label: "neutral" },
    { text: "The video was just average, nothing more, nothing less.", label: "neutral" },
    { text: "I don't have a strong opinion either way on this video.", label: "neutral" },
    { text: "This video was just okay, nothing to write home about.", label: "neutral" },
    { text: "I had a neutral response to this video.", label: "neutral" },
    { text: "The video was average, but not very memorable.", label: "neutral" },
    { text: "I didn't feel particularly positive or negative about this video.", label: "neutral" },
    { text: "I found the content to be uninteresting and unengaging.", label: "negative" },
    { text: "The information provided was incorrect and misleading.", label: "negative" },
    { text: "The presentation was poorly organized and difficult to follow.", label: "negative" },
    { text: "The delivery was monotonous and lacked enthusiasm.", label: "negative" },
    { text: "The experience was frustrating due to frequent technical difficulties.", label: "negative" },
    { text: "I was disappointed by the lack of effort put into this project.", label: "negative" },
    { text: "The production value was low and unprofessional.", label: "negative" },
    { text: "The execution was lacking and could have been much better.", label: "negative" },
    { text: "I was underwhelmed by the overall quality of the presentation.", label: "negative" },
    { text: "The tone was inappropriate and offensive to some viewers.", label: "negative" },
    { text: "The pacing was too slow and made it difficult to stay engaged.", label: "negative" },
    { text: "I was unimpressed by the limited creativity and originality.", label: "negative" },
    { text: "The concept was poorly developed and failed to deliver.", label: "negative" },
    { text: "The attention to detail was lacking and resulted in several mistakes.", label: "negative" },
    { text: "The audio quality was poor and made it difficult to hear the speaker.", label: "negative" },
    { text: "The visuals were poorly executed and added little value to the presentation.", label: "negative" },
    { text: "I was unsatisfied by the overall experience and felt it was a waste of time.", label: "negative" },
    { text: "The resource provided was not helpful and added little value to my learning.", label: "negative" },
    { text: "The instructions were confusing and led to several errors.", label: "negative" },
    { text: "The effort put into this project was insufficient and resulted in subpar work.", label: "negative" },
    { text: "I was disappointed by the lack of professionalism and effort.", label: "negative" },
    { text: "The style was outdated and did not align with current trends.", label: "negative" },
    { text: "The approach was too simplistic and failed to address the complexity of the topic.", label: "negative" },
    { text: "The design was cluttered and difficult to navigate.", label: "negative" },
    { text: "I was underwhelmed by the limited scope and depth of the project.", label: "negative" },
    { text: "The accuracy of the information was questionable and needed to be further validated.", label: "negative" },
    { text: "The argument was weak and lacked evidence to support it.", label: "negative" },
    { text: "I was disappointed by the lack of effort to make the project engaging.", label: "negative" },
    { text: "The experience was unfulfilling and left much to be desired.", label: "negative" },
    { text: "The outcome was not what I had expected and fell short of my expectations.", label: "negative" },
    { text: "I was not impressed by the limited skill and expertise demonstrated.", label: "negative" },
    { text: "The collaboration was ineffective and hindered the success of the project.", label: "negative" },
    { text: "The result was unsatisfactory and required significant improvement.", label: "negative" },
    { text: "The presentation was well done, but lacked the depth I was hoping for.", label: "neutral" },
    { text: "The content was informative, but failed to keep my attention for very long.", label: "neutral" },
    { text: "The delivery was smooth, but the material was not as engaging as I would have liked.", label: "neutral" },
    { text: "I appreciated the effort put into the presentation, but it didn't quite hit the mark.", label: "neutral" },
    { text: "The ideas presented were intriguing, but the execution left something to be desired.", label: "neutral" },
    { text: "The discussion was thoughtful, but lacked the passion I was hoping to see.", label: "neutral" },
    { text: "The analysis was thorough, but didn't bring anything new to the table.", label: "neutral" },
    { text: "The speaker was well-prepared, but their approach didn't resonate with me.", label: "neutral" },
    { text: "The visuals were attractive, but not particularly relevant to the topic at hand.", label: "neutral" },
    { text: "The presentation was polished, but the ideas were not particularly groundbreaking.", label: "neutral" },
    { text: "The information was useful, but the presentation was somewhat dry.", label: "neutral" },
    { text: "The speaker was knowledgeable, but the delivery was lacking in energy.", label: "neutral" },
    { text: "The pacing was good, but the content failed to hold my interest for very long.", label: "neutral" },
    { text: "The insights were interesting, but not particularly surprising.", label: "neutral" },
    { text: "The tone was professional, but didn't really connect with me on a personal level.", label: "neutral" },
    { text: "The subject matter was intriguing, but the delivery was a bit lackluster.", label: "neutral" },
    { text: "The ideas were sound, but the presentation lacked the enthusiasm I was hoping for.", label: "neutral" },
    { text: "The approach was well thought-out, but the final product was underwhelming.", label: "neutral" },
    { text: "The speaker had a good command of the subject, but their delivery was somewhat wooden.", label: "neutral" },
    { text: "The data was well-presented, but not particularly insightful.", label: "neutral" },
    { text: "The speaker was articulate, but the message was not particularly memorable.", label: "neutral" },
    { text: "The presentation was neat and organized, but the content was somewhat predictable.", label: "neutral" },
    { text: "The research was extensive, but the findings were not particularly groundbreaking.", label: "neutral" },
    { text: "The speaker was well-spoken, but the content was not as engaging as I had hoped.", label: "neutral" },
    { text: "The arguments were well-made, but not particularly persuasive.", label: "neutral" },
    { text: "The information was accurate, but the presentation was somewhat lackluster.", label: "neutral" },
    { text: "The examples were well-chosen, but not particularly relevant to the topic at hand.", label: "neutral" },
    { text: "The discussion was thorough, but the conclusion was not particularly surprising.", label: "neutral" },
    { text: "The speaker was confident, but the content was not particularly captivating.", label: "neutral" },
    { text: "The analysis was methodical, but the insights were not particularly surprising.", label: "neutral" },
    { text: "I didn't feel particularly strong emotions one way or the other.", label: "neutral" },
    { text: "The interaction was average and not memorable.", label: "neutral" },
    { text: "I had no clear opinion on the situation.", label: "neutral" },
    { text: "The experience was nothing out of the ordinary.", label: "neutral" },
    { text: "I found the situation to be just okay.", label: "neutral" },
    { text: "I didn't have a strong reaction either way.", label: "neutral" },
    { text: "I wasn't particularly impressed or disappointed.", label: "neutral" },
    { text: "The outcome was as expected and nothing surprising.", label: "neutral" },
    { text: "I had no emotional response to the situation.", label: "neutral" },
    { text: "I found the situation to be just average.", label: "neutral" },
    { text: "The interaction was not particularly noteworthy.", label: "neutral" },
    { text: "I had no strong feelings either positive or negative.", label: "neutral" },
    { text: "I found the experience to be just so-so.", label: "neutral" },
    { text: "The situation didn't leave much of an impression on me.", label: "neutral" },
    { text: "I have no opinion on this situation.", label: "neutral" },
    { text: "The situation was nothing special.", label: "neutral" },
    { text: "I found the experience to be mediocre.", label: "neutral" },
    { text: "I had no strong reaction to the situation.", label: "neutral" },
    { text: "The outcome was average and didn't stand out in any way.", label: "neutral" },
    { text: "Your behavior is rude and disrespectful.", label: "negative" },
    { text: "Your attitude towards this matter is unacceptable.", label: "negative" },
    { text: "You have shown a complete lack of consideration for others.", label: "negative" },
    { text: "Your actions have caused harm and damage.", label: "negative" },
    { text: "Your response was inadequate and unsatisfactory.", label: "negative" },
    { text: "You have demonstrated a lack of responsibility in this situation.", label: "negative" },
    { text: "Your behavior was inappropriate and offensive.", label: "negative" },
    { text: "You have shown no remorse for your actions.", label: "negative" },
    { text: "Your performance was subpar and unacceptable.", label: "negative" },
    { text: "Your communication skills are lacking and ineffective.", label: "negative" },
    { text: "You have made several mistakes that have negatively impacted the outcome.", label: "negative" },
    { text: "Your decision making is flawed and unreliable.", label: "negative" },
    { text: "You have neglected your duties and responsibilities.", label: "negative" },
    { text: "Your behavior is unprofessional and immature.", label: "negative" },
    { text: "You have not followed proper protocol and procedures.", label: "negative" },
    { text: "You have shown a lack of respect for authority and rules.", label: "negative" },
    { text: "Your participation in this project was unsatisfactory and disappointing.", label: "negative" },
    { text: "You have demonstrated a lack of effort and dedication.", label: "negative" },
    { text: "Your contributions to this team have been lacking and insufficient.", label: "negative" },
    { text: "You always have a positive attitude and it inspires others.", label: "positive" },
    { text: "You have a unique talent that sets you apart from others.", label: "positive" },
    { text: "Your attention to detail is impeccable and it shows in your work.", label: "positive" },
    { text: "You have a great sense of humor and always bring a smile to people's faces.", label: "positive" },
    { text: "You have a kind heart and always go above and beyond for others.", label: "positive" },
    { text: "You are a creative and innovative problem solver.", label: "positive" },
    { text: "You are a hard worker and never give up on your goals.", label: "positive" },
    { text: "You are always willing to lend a hand and help others in need.", label: "positive" },
    { text: "You have a keen eye for fashion and always look great.", label: "positive" },
    { text: "You are a natural leader and have a way of bringing people together.", label: "positive" },
    { text: "You are always optimistic and bring a positive energy to every situation.", label: "positive" },
    { text: "You have a great sense of humor and always know how to lighten the mood.", label: "positive" },
    { text: "You are a skilled communicator and always get your point across effectively.", label: "positive" },
    { text: "You are a fantastic listener and always make others feel heard and valued.", label: "positive" },
    { text: "You are always willing to learn and grow, and never stop seeking knowledge.", label: "positive" },
    { text: "You have a great work ethic and are always willing to put in the extra effort.", label: "positive" },
    { text: "You have a talent for connecting with people and making friends easily.", label: "positive" },
    { text: "You are a natural motivator and always inspire others to do their best.", label: "positive" },
    { text: "You have a great sense of adventure and are always up for trying new things.", label: "positive" },
];
